"""empty message

Revision ID: 4817396a0cdb
Revises: f80e43999058
Create Date: 2023-12-27 14:35:35.231820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4817396a0cdb'
down_revision = 'f80e43999058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_server', sa.String(length=120), nullable=True),
    sa.Column('mail_port', sa.Integer(), nullable=True),
    sa.Column('mail_use_tls', sa.Boolean(), nullable=True),
    sa.Column('mail_username', sa.String(length=120), nullable=True),
    sa.Column('mail_password', sa.String(length=120), nullable=True),
    sa.Column('mail_default_sender', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_settings')
    # ### end Alembic commands ###
