"""empty message

Revision ID: 4f0503417057
Revises: bcc917687a11
Create Date: 2024-03-28 09:54:24.592711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0503417057'
down_revision = 'bcc917687a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sub_department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sub_department', ['sub_department_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###
