"""empty message

Revision ID: 9db90361daba
Revises: 
Create Date: 2024-01-07 23:16:44.573688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db90361daba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kdsid_ayar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birlesik_parsel_sayisi', sa.Integer(), nullable=False),
    sa.Column('toplam_arsa_alani_min', sa.Integer(), nullable=False),
    sa.Column('is_site_artis_orani', sa.Float(), nullable=False),
    sa.Column('bos_parsel_artis_orani', sa.Float(), nullable=False),
    sa.Column('diger_parsel_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_3000_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_2000_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_1000_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_750_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_500_artis_orani', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('kdsid_ayar')
    # ### end Alembic commands ###
