"""empty message

Revision ID: a81ee8d91fb4
Revises: 
Create Date: 2024-01-09 13:24:59.032628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81ee8d91fb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayarlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('site_title', sa.String(length=100), nullable=True),
    sa.Column('site_logo', sa.String(length=100), nullable=True),
    sa.Column('google_analytics', sa.String(length=100), nullable=True),
    sa.Column('site_instagram', sa.String(length=100), nullable=True),
    sa.Column('site_facebook', sa.String(length=100), nullable=True),
    sa.Column('site_twitter', sa.String(length=100), nullable=True),
    sa.Column('site_youtube', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.Column('seo_keywords', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kdsid_ayar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birlesik_parsel_sayisi', sa.Integer(), nullable=False),
    sa.Column('toplam_arsa_alani_min', sa.Integer(), nullable=False),
    sa.Column('is_site_artis_orani', sa.Float(), nullable=False),
    sa.Column('bos_parsel_artis_orani', sa.Float(), nullable=False),
    sa.Column('diger_parsel_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_3000_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_2000_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_1000_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_750_artis_orani', sa.Float(), nullable=False),
    sa.Column('arsa_alani_500_artis_orani', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_server', sa.String(length=120), nullable=True),
    sa.Column('mail_port', sa.Integer(), nullable=True),
    sa.Column('mail_use_tls', sa.Boolean(), nullable=True),
    sa.Column('mail_username', sa.String(length=120), nullable=True),
    sa.Column('mail_password', sa.String(length=120), nullable=True),
    sa.Column('mail_default_sender', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modul_ayar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanıcılar_aktif', sa.Boolean(), nullable=True),
    sa.Column('blog_aktif', sa.Boolean(), nullable=True),
    sa.Column('mesajlar_aktif', sa.Boolean(), nullable=True),
    sa.Column('projeler_aktif', sa.Boolean(), nullable=True),
    sa.Column('riskli_yapı_aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('membership_type', sa.String(length=255), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], )
    )
    op.create_table('tbl_projeler',
    sa.Column('proje_id', sa.Integer(), nullable=False),
    sa.Column('proje_adi', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('is_site', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.user_id'], ),
    sa.PrimaryKeyConstraint('proje_id')
    )
    op.create_table('tbl_veri',
    sa.Column('veri_id', sa.Integer(), nullable=False),
    sa.Column('proje_id', sa.Integer(), nullable=True),
    sa.Column('isim', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=15), nullable=True),
    sa.Column('tcno', sa.String(length=11), nullable=True),
    sa.Column('mvid', sa.Float(), nullable=True),
    sa.Column('kdsid', sa.Float(), nullable=True),
    sa.Column('arsaalan', sa.Float(), nullable=True),
    sa.Column('kisiarsaalan', sa.Float(), nullable=True),
    sa.Column('hisseoran', sa.Float(), nullable=True),
    sa.Column('ada', sa.Integer(), nullable=True),
    sa.Column('parsel', sa.Integer(), nullable=True),
    sa.Column('onay_durumu', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proje_id'], ['tbl_projeler.proje_id'], ),
    sa.PrimaryKeyConstraint('veri_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_veri')
    op.drop_table('tbl_projeler')
    op.drop_table('roles_users')
    op.drop_table('tbl_users')
    op.drop_table('role')
    op.drop_table('modul_ayar')
    op.drop_table('mail_settings')
    op.drop_table('kdsid_ayar')
    op.drop_table('ayarlar')
    # ### end Alembic commands ###
