"""empty message

Revision ID: b6c92c0afa47
Revises: 
Create Date: 2023-12-26 19:39:37.589052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c92c0afa47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayarlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('site_title', sa.String(length=100), nullable=True),
    sa.Column('site_logo', sa.String(length=100), nullable=True),
    sa.Column('google_analytics', sa.String(length=100), nullable=True),
    sa.Column('site_instagram', sa.String(length=100), nullable=True),
    sa.Column('site_facebook', sa.String(length=100), nullable=True),
    sa.Column('site_twitter', sa.String(length=100), nullable=True),
    sa.Column('site_youtube', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.Column('seo_keywords', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Ayarlar')
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('Ayarlar',

    )
    op.drop_table('ayarlar')
    # ### end Alembic commands ###
