"""empty message

Revision ID: f80e43999058
Revises: b6c92c0afa47
Create Date: 2023-12-27 13:03:46.579174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80e43999058'
down_revision = 'b6c92c0afa47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modul_ayar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanıcılar_aktif', sa.Boolean(), nullable=True),
    sa.Column('blog_aktif', sa.Boolean(), nullable=True),
    sa.Column('mesajlar_aktif', sa.Boolean(), nullable=True),
    sa.Column('projeler_aktif', sa.Boolean(), nullable=True),
    sa.Column('riskli_yapı_aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modul_ayar')
    # ### end Alembic commands ###
